
# @name Delete all persons
# @no-log
DELETE http://localhost:9000/api/persons
Accept: application/json
###

# @name Post new person
# @no-log
POST http://localhost:9000/api/persons
Content-Type: application/json

{
  "first_name":"An",
  "last_name": "Van den Abbeel"
}
###

# @name Get all persons
# @no-log
GET http://localhost:9000/api/persons
Accept: application/json

###


